### ISSUE TITLE
兄弟，能告知一下如何运行吗？未接触过c  感谢

### ISSUE THREAD

**Issue by ZhangJian0825** [SinnoSong/SecKill#1]

**Comment by SinnoSong** [comment]
https://github.com/SinnoSong/SecKill/releases 这个页面下载最新版本exe文件，使用win10系统直接双击运行。win10之下的系统会自动提示安装.net framework

**Comment by ZhangJian0825** [comment]
谢谢，昨天和今天试了一下   虽然都没抢到  但是能正常运行，快到时间的时候一直发请求。https://miaomiao.scmttec.com/seckill/seckill/checkstock2.do?id=1300  row返回一直是排队中   但是倒计时结束后，点击按钮会进入订单提交的页面，请求链接是不是不一样？

**Comment by ZhangJian0825** [comment]
> https://github.com/SinnoSong/SecKill/releases这个下载最新版本的exe文件，使用win10系统页面直接运行。win10下面的系统会自动提示安装.net框架

谢谢，昨天和今天试了一下没抢到但能正常运行，快到时间的时候一直在发请求。https://miaomiao.scmttec.com/seckill/seckill/checkstock2.do?id=1300 row返回一直是真实的，但是倒计时结束后，点击按钮会进入订单提交的页面，请求链接是不是不一样？

**Comment by SinnoSong** [comment]
目前应该是获取加密参数有问题，需要再调试，最近秒苗小程序可以抢的时候，我会看一下

**Comment by ZhangJian0825** [comment]
> 获取加密参数有问题

好的  麻烦了

**Comment by SinnoSong** [comment]
已修复获取加密参数问题，可使用最新版：https://github.com/SinnoSong/SecKill/releases/tag/v1.0
