### ISSUE TITLE
有关日志记录的问题

### ISSUE THREAD

**Issue by Chris700819** [SinnoSong/SecKill#11]
选择区域之后日志记录会有显示，但选择成员就没有，这个是正常的吗，还是成员没有被选中？选择疫苗之后会弹出一个完成窗口，日志记录会显示“还未到获取st时间,等待...”这个是正常的吗？开始抢之后就显示如下图所示，是没有抢到的意思吗？还是设置上出了问题导致运行出错？
![image](https://user-images.githubusercontent.com/69673935/153435680-cc7e4bda-7b69-4943-8fb4-ca7f75e47ad0.png)

**Comment by SinnoSong** [comment]
成员选择后，没有设置日志记录。截图不全，但应该是没有抢到，软件抢苗的线程那边代码需要修改，最近没有时间所以还没有改

**Comment by Chris700819** [comment]
好的谢谢，等你修改之后我再试试，另祝新年快乐

**Comment by yanjiache** [comment]
选择成员报错
![image](https://user-images.githubusercontent.com/73382341/154408624-57b8fb1e-b411-4dbe-97f8-54b6dad64f48.png)

**Comment by SinnoSong** [comment]
@Chris700819 下午看了代码应该是没有什么问题的，看你的截图应该是获取加密参数的问题，下次有苗可以抢的时候，我会调试下

**Comment by SinnoSong** [comment]
@Chris700819 现在已经更新最新版了。下载最新版使用即可。这个issue我关闭了。
