### ISSUE TITLE
选择成员报错是啥

### ISSUE THREAD

**Issue by yanjiache** [SinnoSong/SecKill#12]
![image](https://user-images.githubusercontent.com/73382341/154408664-eb70f938-f48b-4ab1-88eb-13313a4395ee.png)

**Comment by SinnoSong** [comment]
有可能是你的token和cookie设置问题。

**Comment by SinnoSong** [comment]
@yanjiache 请你参考这个链接使用：https://zhuanlan.zhihu.com/p/449082615
