### ISSUE TITLE
请问一下 抢购时出现如下的日志 是我配置出了问题还是确实没抢到

### ISSUE THREAD

**Issue by DearRichardLi** [SinnoSong/SecKill#13]
···
Thread ID: main,请求获取加密参数ST
Thread ID: main, 成功获取加密参数st:1646099997
Thread ID:9秒杀请求
Thread ID:9,抢购失败: False
Thread ID:9,请求获取加密参数ST
Thread ID:9, 成功获取加密参数ST
Thread ID:9,秒杀请求
Thread ID:9,抢购失败: False
Thread ID:9,请求获取加密参数ST
Thread ID:9, 成功获取加密参数ST
Thread ID:9,秒杀请求
Thread ID:9,抢购失败: False
抢购失败
Thread ID:9,秒杀请求
Thread ID:9,抢购失败: False
···
出现了这样的日志..想请问一下是我配置出了问题吗
token和cookie都正确填写了 能选择接种人 刷新出了列表

**Comment by SinnoSong** [comment]
配置没问题，只是单纯没有抢到。
