### ISSUE TITLE
点击选择成员，出现cood:1001,Msg:false.提示

### ISSUE THREAD

**Issue by IZHOUbin2000** [SinnoSong/SecKill#14]
![微信截图_20220306215103](https://user-images.githubusercontent.com/77671093/156926228-b69a5f17-365c-4eff-aa6a-390913f4b432.png)
![微信截图_20220306215052](https://user-images.githubusercontent.com/77671093/156926230-f9025ba3-451d-4b5e-ab6f-82761e0d480f.png)

**Comment by SinnoSong** [comment]
@IZHOUbin2000 
![image](https://user-images.githubusercontent.com/59649274/156992396-990fe0d0-47ef-4dac-8a53-409cab52b112.png)
不要把wxapptoken这个key和“：”带上
