### ISSUE TITLE
操作频繁了哥

### ISSUE THREAD

**Issue by q1353522961** [SinnoSong/SecKill#17]
![微信图片_20220321090236](https://user-images.githubusercontent.com/96217313/159194009-7110201b-0c09-49ef-b8a6-49fdaa6dd6a6.png)
操作频繁了哥，抢购时间间隔是太短了吗

**Comment by SinnoSong** [comment]
@q1353522961 是的，你现在使用的是最新版吗？

**Comment by q1353522961** [comment]
> @q1353522961 是的，你现在使用的是最新版吗？

是的，1.14

**Comment by SinnoSong** [comment]
> > @q1353522961 是的，你现在使用的是最新版吗？
> 
> 是的，1.14

下午我会看下怎么回事，时间问题

**Comment by q1353522961** [comment]
> > > @q1353522961 是的，你现在使用的是最新版吗？
> > 
> > 
> > 是的，1.14
> 
> 下午我会看下怎么回事，时间问题

好的哥

**Comment by SinnoSong** [comment]
@q1353522961 下载最新版
