### ISSUE TITLE
这个日志反应的流程是正常的吗

### ISSUE THREAD

**Issue by zmm2tysu** [SinnoSong/SecKill#18]
![image](https://user-images.githubusercontent.com/20849786/159217317-7f1f60e9-6500-426c-a33a-a164b1423a64.png)

**Comment by zmm2tysu** [comment]
版本1.14

**Comment by SinnoSong** [comment]
@zmm2tysu 正常的，就是时间设置问题，之前因为“某位用户”说抢的速度不够快所以，调整了。现在看来是速度太快被ban了。我等会更新新版慢一点，抢的时间长一点。

**Comment by zmm2tysu** [comment]
有人抢成功过没...
