### ISSUE TITLE
大哥，软件在正常运行

### ISSUE THREAD

**Issue by q1353522961** [SinnoSong/SecKill#2]
纯小白，全靠百度，看fiddler一直在发送请求还是啥，到时间出了2k多条红色的，不是很懂，希望大哥指点指点，谢谢

**Comment by SinnoSong** [comment]
获取加密参数问题，现在已经修复。可使用最新版release:https://github.com/SinnoSong/SecKill/releases/tag/v1.0

**Comment by Lihengwannafly** [comment]
应该进哪个页面抓cookies呢

**Comment by q1353522961** [comment]
> 应该进哪个页面抓cookies呢

我在个人中心抓的，不然登陆超时

**Comment by Lihengwannafly** [comment]
> 
![image](https://user-images.githubusercontent.com/24928240/147580062-c372bf63-a93b-486f-bce3-b3371e001b3b.png)

**Comment by Lihengwannafly** [comment]
![image](https://user-images.githubusercontent.com/24928240/147580134-ae68bb52-ee36-42f4-9cc1-0366c3166178.png)
这里吗？没有抓到cookie啊

**Comment by Lihengwannafly** [comment]
![image](https://user-images.githubusercontent.com/24928240/147580134-ae68bb52-ee36-42f4-9cc1-0366c3166178.png)
这里吗？没有抓到cookie啊

**Comment by q1353522961** [comment]
> ![image](https://user-images.githubusercontent.com/24928240/147580134-ae68bb52-ee36-42f4-9cc1-0366c3166178.png)这里吗？没有抓到饼干啊

再点一下家庭成员呗
