### ISSUE TITLE
老哥，未知异常是正常现象吗

### ISSUE THREAD

**Issue by q1353522961** [SinnoSong/SecKill#21]
![QQ截图20220322160204](https://user-images.githubusercontent.com/96217313/159434647-3b343edc-8452-40d7-95f1-49a605932f82.png)
老哥，未知异常是正常现象吗

**Comment by 0728xjf** [comment]
一样，成都太热门了，换个限户籍的二三线小城市可能还有戏抢到。。。

**Comment by SinnoSong** [comment]
应该是秒苗服务器响应超时了，大概率因为同时使用秒杀软件的人数过多的原因。

**Comment by q1353522961** [comment]
> 应该是秒苗服务器响应超时了，大概率因为同时使用秒杀软件的人数过多的原因。
好吧
