### ISSUE TITLE
作者大大，能不能优化一下，抢不到啊，跪谢！

### ISSUE THREAD

**Issue by SichunWang** [SinnoSong/SecKill#22]
<img width="199" alt="微信图片_20220322161204" src="https://user-images.githubusercontent.com/102142638/159436229-f982756d-2550-47ab-8461-2227b8fdf610.png">

**Comment by SinnoSong** [comment]
目前只能尽量模拟人的真实操作，秒苗那边肯定做了防止软件抢的。而且同时使用软件抢的人太多了。抢不到也属于正常情况
