### ISSUE TITLE
抓到token后需要把秒苗小程序关掉么？

### ISSUE THREAD

**Issue by zmm2tysu** [SinnoSong/SecKill#23]
关掉的话 token不会失效吧

**Comment by SichunWang** [comment]
> 关掉的话 token不会失效吧

不会

**Comment by zmm2tysu** [comment]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/20849786/159601253-412b41c8-aa54-4db3-a8cd-8be00248acbd.png">

**Comment by zmm2tysu** [comment]
这种情况是不是我多开几个程序也没啥用啊

**Comment by SinnoSong** [comment]
@zmm2tysu 是的，如果多开还会影响正常抢。因为目前每次抢之前都会获取一个加密参数
