### ISSUE TITLE
作者大大，还是需要优化啊，根本抢不到

### ISSUE THREAD

**Issue by SichunWang** [SinnoSong/SecKill#24]
![Uploading ea8f1c316794b1c7f2b6bd9a5df1aa6.png…]()
![image](https://user-images.githubusercontent.com/102142638/159601452-4bed7c91-a82b-499e-95db-c462de771b47.png)

**Comment by SinnoSong** [comment]
目前只能尽量模拟真人操作，而且使用软件抢的人比较多。

**Comment by SichunWang** [comment]
> 

就不能再优化一下了吗？

**Comment by SinnoSong** [comment]
@SichunWang 更新了最新版，可以试一下
