### ISSUE TITLE
开始抢之后日志记录显示获取st失败

### ISSUE THREAD

**Issue by Chris700819** [SinnoSong/SecKill#29]
![image](https://user-images.githubusercontent.com/69673935/162569726-d2ef73e4-7b73-4e03-866f-6dff442b459f.png)
请问这个是怎么回事啊？需要重新登录还是重新抓cookie啊？按理说我还怕cookie变提前半个小时才抓了新的粘上去的，为什么失败？是因为我在手机上也登录了吗？

**Comment by SinnoSong** [comment]
@Chris700819 不能同时登录使用
