### ISSUE TITLE
提示未获取到ST参数

### ISSUE THREAD

**Issue by srxh-max** [SinnoSong/SecKill#33]

**Comment by Christopher-Songs** [comment]
是的，今天的新版，一直提示这个，太难了。。。

**Comment by Fengikjing** [comment]
选择成员报错误码code 1001 Msg：用户登录超时，请重新登录

**Comment by SinnoSong** [comment]
如果token是30分钟前抓的，就有可能所以我在readme里面写了要保持是30分内的token

**Comment by Fengikjing** [comment]
排查到错误了  我新开了issues然后关掉了，readme里面的这个token是：'xzkj=wxapptoken:10:848b46edd7fe69b98680bd3541f29d56_bf246bba2d811ddc1c335f7a98305b51'，软件里面tk要把'xzkj='去掉才能选择成员，然后不报错

**Comment by SinnoSong** [comment]
我的问题，没有把前面的值删除

**Comment by zkydsg** [comment]
就用下exe包还是需要把压缩包解压到文件夹放一起

**Comment by zkydsg** [comment]
兄弟解答下谢谢啦

**Comment by Fengikjing** [comment]
我就用了EXE 没有下载压缩包

**Comment by Fengikjing** [comment]
压缩包你说的是源码吧。。。下载源码你要自己编译的

**Comment by zkydsg** [comment]
> 

谢啦兄弟

**Comment by haiwen1** [comment]
抢到了吗

**Comment by trespassingly** [comment]
蹲有没有抢到的

**Comment by SinnoSong** [comment]
@srxh-max 提示未到时间，等待中  是正常的，到开始抢苗的时候会自动开始抢
