### ISSUE TITLE
选择成员无法使用  报错误码1001(已解决）

### ISSUE THREAD

**Issue by Fengikjing** [SinnoSong/SecKill#34]
![截图_20223425043446](https://user-images.githubusercontent.com/81843759/165051779-e83000a8-d09b-4b9e-87af-6e5dd2dfe741.png)
选择成员无法使用  报错误码1001

**Comment by Fengikjing** [comment]
![截图_20224225044227](https://user-images.githubusercontent.com/81843759/165053263-96328868-90e2-4eb8-a0a3-93e379f84e6f.png)
已解决 第一行为cookie 第二行为token 请更正readme.md的内容，感谢！

**Comment by ouyang-yuxuan** [comment]
我也是遇到了这个问题，怎么解决的。好像在Cookie中已经包含了token
