### ISSUE TITLE
还未到获取st时间，等待中。

### ISSUE THREAD

**Issue by zhonggang666** [SinnoSong/SecKill#35]
![image](https://user-images.githubusercontent.com/54022200/167074155-dca247ba-d4ff-485d-8f64-33168427b5ec.png)

**Comment by Biscuitwo** [comment]
附议

**Comment by Biscuitwo** [comment]
附议，并且到时间后总会慢几秒的时间，日志记录那里有才变化

**Comment by SinnoSong** [comment]
@zhonggang666 时间到开始抢苗的时候会自动抢。显示是正常的
