### ISSUE TITLE
1001用户登陆超时

### ISSUE THREAD

**Issue by ouyang-yuxuan** [SinnoSong/SecKill#36]
![微信截图_20220515094052](https://user-images.githubusercontent.com/36830421/168453693-29aa82ec-fcac-4ea0-84a8-4bc2a5862bf5.png)
![微信截图_20220515094121](https://user-images.githubusercontent.com/36830421/168453694-58ffbaca-6342-4a3d-bd65-5ed1db6177ce.png)

选择用户：登陆用户超时。刚刚才获取的cookie和token，手机电脑都退出了小程序的。

**Comment by SinnoSong** [comment]
重新在小程序获取下cookie和token就可以。

**Comment by ouyang-yuxuan** [comment]
没有用呀，再获取连cookie和token都一样，就算是新的cookie选择成员的时候任然显示登陆超时。都试了很多次了都是一样的。
