### ISSUE TITLE
请问大佬，一上来就“秒杀不存在或已结束”是正常的嘛

### ISSUE THREAD

**Issue by tkl32172** [SinnoSong/SecKill#38]
大佬给看看，更新好几代抢了几十次了还是不行，之前都是两边时间对不上，这次不知道咋回事！谢谢了！
![image](https://user-images.githubusercontent.com/25812959/168968806-5ce6a201-9e28-477a-8a1e-43b5ad456b72.png)

**Comment by xiaomingguo445** [comment]
刚刚我也没抢到

**Comment by dashuwww** [comment]
有抢到了的吗

**Comment by imnicn** [comment]
我也没抢到，估计还得调大提前时间，服务器和本地有时间差，这个得摸索了。

**Comment by SinnoSong** [comment]
> 我也没抢到，估计还得调大提前时间，服务器和本地有时间差，这个得摸索了。

这个问题已经修复过了，会在秒杀前获取服务器时间开始秒杀，设置好提前时间就可以。

**Comment by Syiceeee** [comment]
请问大佬这个交互界面怎么运行出来的

**Comment by SinnoSong** [comment]
@Syiceeee release中下载，然后双击exe直接运行，运行出来是因为他们之前抓包然后把token放到软件中运行得到的。

**Comment by SinnoSong** [comment]
因为约苗后台做了限制，无法判断其逻辑，此项目已失效。 不会再进行维护及更新，故关闭此Issue
