### ISSUE TITLE
每次两次抢购失败就操作频繁是怎么回事呢，改过了很多参数，有合适的参数推荐不

### ISSUE THREAD

**Issue by MedMoss** [SinnoSong/SecKill#39]

**Comment by NEILLEE404** [comment]
有大佬在吗     1. 提前时间设置是不是要看本地网络延迟，再去设置？    2. 还有抢苗时间间隔需不需要修改      每次都显示:抢购失败，操作过于频繁，请稍候再试！  间隔要调慢？
有没有成功的说一下，感谢！

**Comment by SinnoSong** [comment]
因为约苗后台做了限制，无法判断其逻辑，此项目已失效。 不会再进行维护及更新，故关闭此Issue
