### ISSUE TITLE
秒苗在抢之前，和抢之后，ID会变。

### ISSUE THREAD

**Issue by rangx** [SinnoSong/SecKill#40]
如题。导致现在这个程序抢不到

**Comment by SinnoSong** [comment]
@rangx 有时间我会测试下，疫苗Id是在开始秒杀之后变化一次，然后后面保持不变吗?

**Comment by dashuwww** [comment]
就没看到有人用这个抢到过o(╥﹏╥)o 太难了

**Comment by SinnoSong** [comment]
> 如题。导致现在这个程序抢不到

![image](https://user-images.githubusercontent.com/59649274/174270906-9046a062-252f-4562-8b5c-7151d2044859.png)
对比了开抢前和开抢后的Id是一致的。
