### ISSUE TITLE
抢不到哎，试了很多次

### ISSUE THREAD

**Issue by 32haoyangmao** [SinnoSong/SecKill#43]
如图
![图片](https://user-images.githubusercontent.com/94029167/172342313-8fd26112-ccd4-41fd-b1c2-2bb690e2e9e5.png)

**Comment by kiritoghy** [comment]
软件没抢到，自己手动抢抢到了

**Comment by 32haoyangmao** [comment]
> 软件没抢到，自己手动抢抢到了

那你有点牛皮，，，我连点也试过，抢不到

**Comment by 32haoyangmao** [comment]
> 软件没抢到，自己手动抢抢到了

那你有点np，我之前连点器都抢不到

**Comment by Syiceeee** [comment]
请问这个交互界面是怎么运行出来的

**Comment by SinnoSong** [comment]
因为约苗后台做了限制，无法判断其逻辑，此项目已失效。 不会再进行维护及更新，故关闭此Issue
