### ISSUE TITLE
选择成员点击之后，显示Code:1001, Msg: False

### ISSUE THREAD

**Issue by Lihengwannafly** [SinnoSong/SecKill#5]
选择成员点击之后，显示Code:1001, Msg: False。刷新疫苗列表能够显示出来。

**Comment by SinnoSong** [comment]
@Lihengwannafly 你好，没有明白你说的什么意思，你可以再详细描述一次吗？

**Comment by Lihengwannafly** [comment]
> @Lihengwannafly 你好，没有明白你说的什么意思，你可以再详细描述一次吗？

这个问题解决了，应该填写cookie和tk之后直接保存，而不是解析后再报错。
