### ISSUE TITLE
程序一直提醒ST参数有异常

### ISSUE THREAD

**Issue by Timekko** [SinnoSong/SecKill#6]
![87e19bedac909db43eae4906ebc3f9f](https://user-images.githubusercontent.com/97569962/149046221-73cf479e-5084-4fb5-a9d9-168373f4e94c.png)
抢购失败后显示如下，这个只是因为没有抢到嘛？

**Comment by SinnoSong** [comment]
@Timekko 不确定是什么问题，我需要在下次可以抢的时候调试看下

**Comment by madlifer** [comment]
![截图_20223218033249](https://user-images.githubusercontent.com/28928374/149890993-5f5214c9-223f-45d3-8be9-7a8b051e4a4f.png)

这个是有问题还是正常情况？

**Comment by SinnoSong** [comment]
@madlifer 应该是有问题的，下次哪里可以抢购请提前@我，我会再看下这个问题

**Comment by madlifer** [comment]
@SinnoSong   定位到成都 今天15点有3针  你可以试下

**Comment by SinnoSong** [comment]
@madlifer 看到了。但是我们公司下午开会，有机会我会调试一下。

**Comment by SinnoSong** [comment]
> @madlifer 看到了。但是我们公司下午开会，有机会我会调试一下。

@madlifer 下午开会没有看，要再等等了。

**Comment by madlifer** [comment]
@SinnoSong  似乎没有问题了  应该是重复录入了cookies和tk的问题  我昨天试了一下 虽然还是抢不到 但是不报错了

**Comment by SinnoSong** [comment]
@madlifer 好的，那我关闭这个issue
