### ISSUE TITLE
设置参数那里上面没法粘贴进去呀

### ISSUE THREAD

**Issue by zhq1** [SinnoSong/SecKill#8]
设置参数那里上面没法粘贴进去呀

**Comment by SinnoSong** [comment]
是粘贴到下面的两个输出框中的

**Comment by zhq1** [comment]
大佬抢到过没  早上我是开了那个jar和这个一起抢 都没抢到，感觉时间还需要稍微调整一下，不然程序会提前发起抢购请求，导致到点了之后 操作过于频繁,请稍后再试!

**Comment by SinnoSong** [comment]
@zhq1 目前我这个版本设置的是抢10秒，因为目前使用软件抢的多太多了，所以抢不到。

**Comment by zhq1** [comment]
我自己修改修改时间看看，想整个苗太难了  太多黄牛了

**Comment by madlifer** [comment]
@SinnoSong  我也遇到这个问题 那个页面粘贴不进去，你加个解析吧  原始cookies需要解析一下  我现在是用原版seckill解析出来后 复制粘贴到这个程序里的... 就很尬

**Comment by SinnoSong** [comment]
@madlifer @zhq1 
![image](https://user-images.githubusercontent.com/59649274/150348505-1804cea0-81e0-4399-a542-0e0e781d1f99.png)
是在这里填写token和cookie的。上面只是用来展示的。
